# Generated by Django 3.2.6 on 2021-08-31 23:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('cat', 'Cat'), ('dog', 'Dog'), ('bird', 'Bird'), ('rodent', 'Rodent'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('ferret', 'Ferret'), ('other', 'Other')], default='cat', max_length=7)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='female', max_length=6)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('food', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
