# Generated by Django 3.2.6 on 2021-08-31 18:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=6)),
                ('age', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('food', models.CharField(max_length=20)),
                ('notes', models.TextField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
